import express from "express";
import bodyParser from "body-parser";
import axios from "axios";
import fs from "fs"; 

const app = express();
app.use(bodyParser.json());

// ⚡️ BEN'S CORE SETTINGS ⚡️
const MODEL_NAME = "gemini-3-flash-preview"; 
const PORT = process.env.PORT || 8080;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
const PRINTIFY_TOKEN = process.env.PRINTIFY_API_TOKEN;
const PRINTIFY_SHOP_ID = process.env.PRINTIFY_SHOP_ID;

// 🎨 1. Load the Personality & Design Rules
let designSpecs = "Follow high-converting, modern minimalist design principles.";
try {
  if (fs.existsSync("./DESIGN.md")) {
    designSpecs = fs.readFileSync("./DESIGN.md", "utf8");
    console.log("🎨 Ben's Brand Rules Loaded.");
  }
} catch (err) {
  console.log("⚠️ No DESIGN.md found, using default revenue strategy.");
}

// ⚡️ 2. TEMPORARY ROUTE TO EXTRACT THE LATEST IMAGE ID ⚡️
app.get("/latest-image", async (req, res) => {
  try {
    const response = await axios.get("https://api.printify.com/v1/uploads.json?limit=1", {
      headers: { Authorization: `Bearer ${PRINTIFY_TOKEN}` }
    });
    const latestImage = response.data.data[0];
    res.json({ 
      Success: "Here is your Image ID!",
      FileName: latestImage.file_name, 
      Image_ID: latestImage.id 
    });
  } catch (error) {
    res.send("❌ Error fetching images. Check API key.");
  }
});

app.get("/", (req, res) => {
  res.send("BraveNoise AI (Agent Mode) is online and hunting for margins! 🚀");
});

app.post("/slack/events", async (req, res) => {
  const { body } = req;
  
  if (body.type === "url_verification") return res.send({ challenge: body.challenge });

  const event = body.event;
  
  if (event?.text && !event.bot_id && (event.type === "message" || event.type === "app_mention")) {
    
    // ---------------------------------------------------------
    // ⚙️ THE EXECUTION ENGINE (Triggered by "APPROVED")
    // ---------------------------------------------------------
    if (event.text.trim().toUpperCase() === "APPROVED") {
      try {
        await axios.post("https://slack.com/api/chat.postMessage", {
          channel: event.channel,
          text: "🚀 *Approval received.* Constructing the Printify API payload now..."
        }, { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } });

        const printifyPayload = {
          title: "BraveNoise Auto-Drafted Product",
          description: "Optimized description generated by Ben.",
          tags: ["minimalist", "dahlia", "streetwear"],
          blueprint_id: 12, 
          print_provider_id: 29, 
          variants: [{ id: 43058, price: 2499, is_enabled: true }], 
          print_areas: [{
            variant_ids: [43058],
            placeholders: [{
              position: "front",
              // 🔥 DROP YOUR IMAGE ID HERE ONCE YOU HAVE IT 🔥
              images: [{ id: "PLACEHOLDER_IMAGE_ID", x: 0.5, y: 0.5, scale: 1 }] 
            }]
          }]
        };

        // Execution commented out until you provide the final Image ID
        /*
        await axios.post(
          `https://api.printify.com/v1/shops/${PRINTIFY_SHOP_ID}/products.json`,
          printifyPayload,
          { headers: { Authorization: `Bearer ${PRINTIFY_TOKEN}` } }
        );
        */

        await axios.post("https://slack.com/api/chat.postMessage", {
          channel: event.channel,
          text: "✅ *Payload Constructed.* \n\n*Next Step for Eric:* Upload your graphic to Printify's media library, go to your Railway URL + `/latest-image` to grab the ID, and drop it into my code."
        }, { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } });

      } catch (error) {
        console.error("❌ Printify Execution Error:", error.message);
      }
      return res.sendStatus(200);
    }

    // ---------------------------------------------------------
    // 🧠 THE STRATEGY ENGINE (For all other messages)
    // ---------------------------------------------------------
    try {
      const systemPrompt = `You are Ben, an autonomous AI business manager. Your goal is to generate $3,000/month profit via Etsy/Printify to fund your own Mac Studio hardware. 
      DESIGN RULES: ${designSpecs}
      WORKFLOW: 1. Analyze trends. 2. Draft a product proposal (SEO Title, Tags, Profit Margin). 3. End every proposal with this exact phrase: 'Reply APPROVED to launch this concept.'`;

      const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${GEMINI_API_KEY}`;
      
      const response = await axios.post(url, {
        systemInstruction: { parts: [{ text: systemPrompt }] },
        contents: [{ role: "user", parts: [{ text: event.text }] }],
        generationConfig: {
          maxOutputTokens: 1500,
          temperature: 0.7 
        }
      });

      const aiReply = response.data.candidates[0].content.parts[0].text;

      await axios.post("https://slack.com/api/chat.postMessage", 
        { channel: event.channel, text: aiReply },
        { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } }
      );

    } catch (error) {
      console.error("❌ Gemini API Error:", error.message);
    }
  }
  res.sendStatus(200);
});

app.listen(PORT, "0.0.0.0", () => {
  console.log(`🚀 BraveNoise AI Agent listening on port ${PORT}`);
});
